name: Build Release and Draft Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-linux-binary:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Release Build
        run: cargo build --verbose --release
      - name: Upload Artiface
        uses: actions/upload-artifact@v3
        with:
          name: chatsh-linux
          path: target/release/chatsh
  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release Build
        run: cargo build --verbose --release
      - name: Upload Artiface
        uses: actions/upload-artifact@v3
        with:
          name: chatsh-darwin
          path: target/release/chatsh
  draft-release:
    needs: [build-linux-binary, build-darwin-binary]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Make directories
        run: |
          mkdir -p ./chatsh-build/linux
          mkdir -p ./chatsh-build/darwin
      - name: Download linux binaries
        uses: actions/download-artifact@v3
        with:
          name: chatsh-linux
          path: ./chatsh-build/linux
      - name: Download darwin binaries
        uses: actions/download-artifact@v3
        with:
          name: cathsh-darwin
          path: ./chatsh-build/darwin
      - name: Merge checksum file
        run: |
          cd ./chatsh-build
          cat ./darwin/chatsh*checksums.txt >> checksums.txt
          cat ./linux/chatsh*checksums.txt >> checksums.txt
          rm ./darwin/chatsh*checksums.txt
          rm ./linux/chatsh*checksums.txt
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --config scripts/.goreleaser-release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
